TurnID = 0

[Settlements]
  [Settlements.Aelyndar]
    Name = "Aelyndar"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = false
    Allegiance = "Thrane"
    Occupied = false
    Population = 4000

    [Settlements.Aelyndar.HP]
      Current = 40
      Max = 40

    [[Settlements.Aelyndar.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 1

    [[Settlements.Aelyndar.Fortifications]]
      Name = "Wooden Battlements"
      Type = 1
      DefenseModifier = 4
      AttackModifier = 1

  [Settlements."Angwar Keep"]
    Name = "Angwar Keep"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 7000

    [Settlements."Angwar Keep".HP]
      Current = 70
      Max = 70

    [[Settlements."Angwar Keep".Fortifications]]
      Name = "Stone Walls"
      Type = 0
      DefenseModifier = 15
      AttackModifier = 3

    [[Settlements."Angwar Keep".Fortifications]]
      Name = "Stone Battlements"
      Type = 1
      DefenseModifier = 7
      AttackModifier = 2

  [Settlements."Arythawn Keep"]
    Name = "Arythawn Keep"
    AttackRoll = ["d20"]
    DamageRoll = ["d6"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 5000
    [Settlements."Arythawn Keep".HP]
      Current = 50
      Max = 50

    [[Settlements."Arythawn Keep".Fortifications]]
      Name = "Stone Walls"
      Type = 0
      DefenseModifier = 15
      AttackModifier = 3

    [[Settlements."Arythawn Keep".Fortifications]]
      Name = "Stone Battlements"
      Type = 1
      DefenseModifier = 7
      AttackModifier = 2

  [Settlements.Athandra]
    Name = "Athandra"
    AttackRoll = ["d20"]
    DamageRoll = ["d4-1"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 20000
    [Settlements.Athandra.HP]
      Current = 200
      Max = 200

    [[Settlements.Athandra.Fortifications]]
      Name = "Stone Walls"
      Type = 0
      DefenseModifier = 15
      AttackModifier = 3

    [[Settlements.Athandra.Fortifications]]
      Name = "Wooden Battlements"
      Type = 1
      DefenseModifier = 4
      AttackModifier = 1

  [Settlements.Auxylgard]
    Name = "Auxylgard"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 3000

    [Settlements.Auxylgard.HP]
      Current = 30
      Max = 30

    [[Settlements.Auxylgard.Fortifications]]
      Name = "Stone Walls"
      Type = 0
      DefenseModifier = 15
      AttackModifier = 3

    [[Settlements.Auxylgard.Fortifications]]
      Name = "Stone Battlements"
      Type = 1
      DefenseModifier = 7
      AttackModifier = 2

    [[Settlements.Auxylgard.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0

#Left off here
  [Settlements.Avaroth]
    Name = "Avaroth"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Avaroth.HP]
      Current = 100
      Max = 100

    [[Settlements.Avaroth.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Danthaven]
    Name = "Danthaven"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Danthaven.HP]
      Current = 100
      Max = 100

    [[Settlements.Danthaven.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Daskaran]
    Name = "Daskaran"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Daskaran.HP]
      Current = 100
      Max = 100

    [[Settlements.Daskaran.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Flamekeep]
    Name = "Flamekeep"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Flamekeep.HP]
      Current = 100
      Max = 100

    [[Settlements.Flamekeep.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements."Fort Light"]
    Name = "Fort Light"
    AttackRoll = ["d20"]
    DamageRoll = ["d20"]
    HasWarGuard = true
    Allegiance = "Aundair"
    Occupied = true
    Population = 0
    [Settlements."Fort Light".HP]
      Current = 100
      Max = 100

    [[Settlements."Fort Light".Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Lessyk]
    Name = "Lessyk"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Lessyk.HP]
      Current = 100
      Max = 100

    [[Settlements.Lessyk.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Morningcrest]
    Name = "Morningcrest"
    AttackRoll = ["d20"]
    DamageRoll = ["d20"]
    HasWarGuard = true
    Allegiance = "Aundair"
    Occupied = true
    Population = 0
    [Settlements.Morningcrest.HP]
      Current = 100
      Max = 100

    [[Settlements.Morningcrest.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Nathyrr]
    Name = "Nathyrr"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Nathyrr.HP]
      Current = 100
      Max = 100

    [[Settlements.Nathyrr.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Olath]
    Name = "Olath"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Olath.HP]
      Current = 100
      Max = 100

    [[Settlements.Olath.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Rellekor]
    Name = "Rellekor"
    AttackRoll = ["d20"]
    DamageRoll = ["d20"]
    HasWarGuard = true
    Allegiance = "Aundair"
    Occupied = true
    Population = 0
    [Settlements.Rellekor.HP]
      Current = 100
      Max = 100

    [[Settlements.Rellekor.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Shadukar]
    Name = "Shadukar"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Shadukar.HP]
      Current = 100
      Max = 100

    [[Settlements.Shadukar.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Sharavacion]
    Name = "Sharavacion"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Sharavacion.HP]
      Current = 100
      Max = 100

    [[Settlements.Sharavacion.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Sigilstar]
    Name = "Sigilstar"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Sigilstar.HP]
      Current = 100
      Max = 100

    [[Settlements.Sigilstar.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements."Silvercliff Castle"]
    Name = "Silvercliff Castle"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements."Silvercliff Castle".HP]
      Current = 100
      Max = 100

    [[Settlements."Silvercliff Castle".Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Siyar]
    Name = "Siyar"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Siyar.HP]
      Current = 100
      Max = 100

    [[Settlements.Siyar.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Tellyn]
    Name = "Tellyn"
    AttackRoll = ["d20"]
    DamageRoll = ["d20"]
    HasWarGuard = true
    Allegiance = "Aundair"
    Occupied = true
    Population = 0
    [Settlements.Tellyn.HP]
      Current = 100
      Max = 100

    [[Settlements.Tellyn.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Thaliost]
    Name = "Thaliost"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Thaliost.HP]
      Current = 100
      Max = 100

    [[Settlements.Thaliost.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements."The Thornwood"]
    Name = "The Thornwood"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements."The Thornwood".HP]
      Current = 100
      Max = 100

    [[Settlements."The Thornwood".Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Traelyn]
    Name = "Traelyn"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Traelyn.HP]
      Current = 100
      Max = 100

    [[Settlements.Traelyn.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0
  [Settlements.Valiron]
    Name = "Valiron"
    AttackRoll = ["d20"]
    DamageRoll = ["d4"]
    HasWarGuard = true
    Allegiance = "Thrane"
    Occupied = false
    Population = 0
    [Settlements.Valiron.HP]
      Current = 100
      Max = 100

    [[Settlements.Valiron.Fortifications]]
      Name = "Wooden Walls"
      Type = 0
      DefenseModifier = 10
      AttackModifier = 0

[Armies]
  [Armies."Demon's Bane"]
    Name = "Demon's Bane"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Thrane"
    Destroyed = false
    [Armies."Demon's Bane".HP]
      Current = 100
      Max = 100
  [Armies."Fifth Cog"]
    Name = "Fifth Cog"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."Fifth Cog".HP]
      Current = 100
      Max = 100
  [Armies."Fifth Host"]
    Name = "Fifth Host"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Thrane"
    Destroyed = false
    [Armies."Fifth Host".HP]
      Current = 100
      Max = 100
  [Armies."First Chain"]
    Name = "First Chain"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."First Chain".HP]
      Current = 100
      Max = 100
  [Armies."First Cog"]
    Name = "First Cog"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."First Cog".HP]
      Current = 100
      Max = 100
  [Armies."First Gear"]
    Name = "First Gear"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."First Gear".HP]
      Current = 100
      Max = 100
  [Armies."First Host"]
    Name = "First Host"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Thrane"
    Destroyed = false
    [Armies."First Host".HP]
      Current = 100
      Max = 100
  [Armies."First Surgeons"]
    Name = "First Surgeons"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Thrane"
    Destroyed = false
    [Armies."First Surgeons".HP]
      Current = 100
      Max = 100
  [Armies."Fourth Cog"]
    Name = "Fourth Cog"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."Fourth Cog".HP]
      Current = 100
      Max = 100
  [Armies."Fourth Host"]
    Name = "Fourth Host"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Thrane"
    Destroyed = false
    [Armies."Fourth Host".HP]
      Current = 100
      Max = 100
  [Armies.Lightbringers]
    Name = "Lightbringers"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Thrane"
    Destroyed = false
    [Armies.Lightbringers.HP]
      Current = 100
      Max = 100
  [Armies."Second Chain"]
    Name = "Second Chain"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."Second Chain".HP]
      Current = 100
      Max = 100
  [Armies."Second Cog"]
    Name = "Second Cog"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."Second Cog".HP]
      Current = 100
      Max = 100
  [Armies."Second Gear"]
    Name = "Second Gear"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."Second Gear".HP]
      Current = 100
      Max = 100
  [Armies."Second Host"]
    Name = "Second Host"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Thrane"
    Destroyed = false
    [Armies."Second Host".HP]
      Current = 100
      Max = 100
  [Armies."Second Surgeons"]
    Name = "Second Surgeons"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Thrane"
    Destroyed = false
    [Armies."Second Surgeons".HP]
      Current = 100
      Max = 100
  [Armies."Sixth Host"]
    Name = "Sixth Host"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Thrane"
    Destroyed = false
    [Armies."Sixth Host".HP]
      Current = 100
      Max = 100
  [Armies."The Blade"]
    Name = "The Blade"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."The Blade".HP]
      Current = 100
      Max = 100
  [Armies."The Cinch"]
    Name = "The Cinch"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."The Cinch".HP]
      Current = 100
      Max = 100
  [Armies."The Hammer"]
    Name = "The Hammer"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."The Hammer".HP]
      Current = 100
      Max = 100
  [Armies."Third Cog"]
    Name = "Third Cog"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Aundair"
    Destroyed = false
    [Armies."Third Cog".HP]
      Current = 100
      Max = 100
  [Armies."Third Host"]
    Name = "Third Host"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Thrane"
    Destroyed = false
    [Armies."Third Host".HP]
      Current = 100
      Max = 100
  [Armies.Truthspeakers]
    Name = "Truthspeakers"
    AC = 19
    AttackRoll = ["d20"]
    DamageRoll = ["d8"]
    Location = "UNSET_LOCATION"
    Destination = "UNSET_LOCATION"
    Allegiance = "Thrane"
    Destroyed = false
    [Armies.Truthspeakers.HP]
      Current = 100
      Max = 100

[Actors]
  [Actors.Aundair]
    Name = "Aundair"
  [Actors.Thrane]
    Name = "Thrane"
